extract_questions_research_task:
  description: >
    Analyze the provided content titled "{title}" and extract all the questions related to CrewAI. 
    The content is as follows:
    
    "{user_content}"

    Then, conduct research to find the most accurate answers using various online resources.
  expected_output: >
    A list of extracted questions along with their researched answers.
  agent: crewai_research_agent

answer_formulation_task:
  description: >
    Use the researched answers from "{title}" to craft well-structured and professional responses.
  expected_output: >
    A detailed and well-formatted set of answers, each corresponding to a question.
  agent: crewai_customer_support_agent

email_response_task:
  description: >
    Format the answers into a professional email response with the subject "{title}" and the following content:

    "{user_content}"

    Ensure clarity, friendliness, and completeness in the final message.
    Set the sender name to Javier and do not provide contact information.
  expected_output: >
    A customer support email containing answers to all the extracted questions.
  agent: crewai_customer_support_agent
